services:
  discord-bot:
    build: .
    container_name: project-bonk-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - bot-network
    
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "python", "-c", "import asyncio; print('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bot-network:
    driver: bridge
